---
steps:
- name: gcr.io/leszek-jinx-main/terraform-validator
  entrypoint: terraform
  dir: /
  args:
  - init
- name: gcr.io/leszek-jinx-main/terraform-validator
  dir: /
  entrypoint: terraform
  args:
  - plan
  - -out=terraform.plan
- name: gcr.io/leszek-jinx-main/terraform-validator
  entrypoint: "/bin/bash"
  args: ['-c', 'terraform show -json terraform.plan > terraform.json']
  dir: /
- name: gcr.io/leszek-jinx-main/terraform-validator
  dir: /
  args:
  - validate
  - terraform.json
  - --policy-path=/
  - "leszek-jinx-main"
