---
steps:
- name: gcr.io/leszek-jinx-main/terraform-validator
  entrypoint: terraform
  args:
  - init
- name: gcr.io/leszek-jinx-main/terraform-validator
  entrypoint: terraform
  args:
  - plan
  - -out=terraform.plan
- name: gcr.io/leszek-jinx-main/terraform-validator
  entrypoint: "/bin/bash"
  args: ['-c', 'terraform show -json terraform.plan > terraform.json']
- name: gcr.io/leszek-jinx-main/terraform-validator
  args:
  - validate
  - terraform.json
  - --policy-path=policy-library/
